"""Lifestyle tag definitions and assignment logic.

Comprehensive pool of ~400-500 lifestyle/behavioral tags organized in 12 groups.
Each tag has a base prevalence rate and demographic-conditional modifiers.
Tags are assigned to agents probabilistically during population generation.
"""

import random
from pydantic import BaseModel, Field


class LifestyleTagDef(BaseModel):
    """Definition of a single lifestyle tag."""

    id: str
    group: str
    subgroup: str
    label_ja: str
    base_rate: float = Field(ge=0.0, le=1.0)
    modifiers: dict[str, float] = Field(default_factory=dict)
    forces_boost: dict[str, float] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Tag definitions: 12 groups × 30-45 tags each
# ---------------------------------------------------------------------------
# Modifier keys use "dimension:value" format, e.g. "age_band:young"
#   age_band: young (15-29), middle (30-49), senior (50+)
#   gender: male, female
#   region: kanto, kansai, chubu, kyushu, tohoku, hokkaido, chugoku, shikoku
#   income_level: low, middle, high
#   household_type: single, couple, family_young, family_school, elderly
# Modifier values are multiplicative: final_rate = base_rate × Π(modifiers)

_TAGS: list[dict] = [
    # =========================================================================
    # GROUP: pet (~30 tags)
    # =========================================================================
    # --- subgroup: dog ---
    {"id": "pet_dog_small", "group": "pet", "subgroup": "dog", "label_ja": "小型犬の飼い主",
     "base_rate": 0.06, "modifiers": {"household_type:family_young": 1.4, "household_type:family_school": 1.5, "household_type:single": 0.6, "household_type:elderly": 1.3, "region:kanto": 1.1},
     "forces_boost": {"unmet_need_severity": 0.1, "life_event_trigger": 0.05}},
    {"id": "pet_dog_medium", "group": "pet", "subgroup": "dog", "label_ja": "中型犬の飼い主",
     "base_rate": 0.03, "modifiers": {"household_type:family_young": 1.3, "household_type:family_school": 1.4, "region:hokkaido": 1.3, "region:tohoku": 1.2, "household_type:single": 0.4},
     "forces_boost": {"unmet_need_severity": 0.1}},
    {"id": "pet_dog_large", "group": "pet", "subgroup": "dog", "label_ja": "大型犬の飼い主",
     "base_rate": 0.015, "modifiers": {"household_type:family_school": 1.5, "income_level:high": 1.4, "region:hokkaido": 1.5, "household_type:single": 0.3},
     "forces_boost": {"unmet_need_severity": 0.12}},
    {"id": "pet_dog_puppy", "group": "pet", "subgroup": "dog", "label_ja": "子犬を飼い始めた",
     "base_rate": 0.01, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2},
     "forces_boost": {"life_event_trigger": 0.15, "unmet_need_severity": 0.1}},
    {"id": "pet_dog_senior", "group": "pet", "subgroup": "dog", "label_ja": "シニア犬の飼い主",
     "base_rate": 0.02, "modifiers": {"age_band:senior": 1.4, "household_type:elderly": 1.5},
     "forces_boost": {"unmet_need_severity": 0.15, "current_solution_frustration": 0.1}},
    {"id": "pet_dog_multiple", "group": "pet", "subgroup": "dog", "label_ja": "多頭飼い（犬）",
     "base_rate": 0.008, "modifiers": {"income_level:high": 1.5, "household_type:family_school": 1.3},
     "forces_boost": {"unmet_need_severity": 0.12}},
    # --- subgroup: cat ---
    {"id": "pet_cat_indoor", "group": "pet", "subgroup": "cat", "label_ja": "室内猫の飼い主",
     "base_rate": 0.07, "modifiers": {"household_type:single": 1.3, "household_type:couple": 1.2, "age_band:young": 1.2, "region:kanto": 1.1},
     "forces_boost": {"unmet_need_severity": 0.08}},
    {"id": "pet_cat_outdoor", "group": "pet", "subgroup": "cat", "label_ja": "外猫も飼う飼い主",
     "base_rate": 0.02, "modifiers": {"region:tohoku": 1.3, "region:kyushu": 1.2, "household_type:elderly": 1.3},
     "forces_boost": {"unmet_need_severity": 0.08}},
    {"id": "pet_cat_multiple", "group": "pet", "subgroup": "cat", "label_ja": "多頭飼い（猫）",
     "base_rate": 0.015, "modifiers": {"household_type:single": 1.2, "income_level:high": 1.3},
     "forces_boost": {"unmet_need_severity": 0.1}},
    {"id": "pet_cat_kitten", "group": "pet", "subgroup": "cat", "label_ja": "子猫を飼い始めた",
     "base_rate": 0.01, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.1},
     "forces_boost": {"life_event_trigger": 0.12}},
    {"id": "pet_cat_senior", "group": "pet", "subgroup": "cat", "label_ja": "シニア猫の飼い主",
     "base_rate": 0.02, "modifiers": {"age_band:senior": 1.3, "household_type:elderly": 1.4},
     "forces_boost": {"unmet_need_severity": 0.12}},
    # --- subgroup: small_animal ---
    {"id": "pet_hamster", "group": "pet", "subgroup": "small_animal", "label_ja": "ハムスターの飼い主",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.5, "household_type:family_young": 1.4, "household_type:single": 1.2},
     "forces_boost": {"unmet_need_severity": 0.06}},
    {"id": "pet_rabbit", "group": "pet", "subgroup": "small_animal", "label_ja": "うさぎの飼い主",
     "base_rate": 0.015, "modifiers": {"age_band:young": 1.3, "gender:female": 1.3, "household_type:family_young": 1.3},
     "forces_boost": {"unmet_need_severity": 0.06}},
    {"id": "pet_guinea_pig", "group": "pet", "subgroup": "small_animal", "label_ja": "モルモットの飼い主",
     "base_rate": 0.005, "modifiers": {"household_type:family_young": 1.5, "household_type:family_school": 1.4},
     "forces_boost": {"unmet_need_severity": 0.05}},
    {"id": "pet_ferret", "group": "pet", "subgroup": "small_animal", "label_ja": "フェレットの飼い主",
     "base_rate": 0.003, "modifiers": {"age_band:young": 1.5, "income_level:high": 1.3},
     "forces_boost": {"unmet_need_severity": 0.06}},
    # --- subgroup: reptile_fish ---
    {"id": "pet_fish_tropical", "group": "pet", "subgroup": "reptile_fish", "label_ja": "熱帯魚の飼い主",
     "base_rate": 0.025, "modifiers": {"gender:male": 1.3, "age_band:middle": 1.2, "income_level:high": 1.3},
     "forces_boost": {"unmet_need_severity": 0.05}},
    {"id": "pet_fish_goldfish", "group": "pet", "subgroup": "reptile_fish", "label_ja": "金魚・メダカの飼い主",
     "base_rate": 0.03, "modifiers": {"household_type:family_young": 1.4, "household_type:family_school": 1.3, "age_band:senior": 1.2},
     "forces_boost": {"unmet_need_severity": 0.04}},
    {"id": "pet_reptile", "group": "pet", "subgroup": "reptile_fish", "label_ja": "爬虫類の飼い主",
     "base_rate": 0.01, "modifiers": {"gender:male": 1.5, "age_band:young": 1.5},
     "forces_boost": {"unmet_need_severity": 0.06, "novelty_appeal": 0.05}},
    {"id": "pet_aquarium", "group": "pet", "subgroup": "reptile_fish", "label_ja": "アクアリウム愛好家",
     "base_rate": 0.015, "modifiers": {"gender:male": 1.4, "income_level:high": 1.3, "age_band:middle": 1.2},
     "forces_boost": {"unmet_need_severity": 0.05}},
    # --- subgroup: bird ---
    {"id": "pet_bird_small", "group": "pet", "subgroup": "bird", "label_ja": "小鳥の飼い主（インコ等）",
     "base_rate": 0.02, "modifiers": {"household_type:family_young": 1.3, "household_type:elderly": 1.3, "gender:female": 1.2},
     "forces_boost": {"unmet_need_severity": 0.05}},
    {"id": "pet_bird_parrot", "group": "pet", "subgroup": "bird", "label_ja": "オウム・大型鳥の飼い主",
     "base_rate": 0.005, "modifiers": {"income_level:high": 1.5, "age_band:senior": 1.3},
     "forces_boost": {"unmet_need_severity": 0.07}},
    # --- subgroup: other ---
    {"id": "pet_insect", "group": "pet", "subgroup": "other", "label_ja": "昆虫飼育（カブトムシ等）",
     "base_rate": 0.025, "modifiers": {"household_type:family_young": 2.0, "household_type:family_school": 1.8, "gender:male": 1.3},
     "forces_boost": {"unmet_need_severity": 0.04}},
    {"id": "pet_none_wants", "group": "pet", "subgroup": "other", "label_ja": "ペットを飼いたいが飼えない",
     "base_rate": 0.08, "modifiers": {"household_type:single": 1.3, "age_band:young": 1.4},
     "forces_boost": {"current_solution_frustration": 0.15, "unmet_need_severity": 0.1}},
    {"id": "pet_allergy", "group": "pet", "subgroup": "other", "label_ja": "ペットアレルギー持ち",
     "base_rate": 0.05, "modifiers": {},
     "forces_boost": {"performance_uncertainty": 0.1}},
    {"id": "pet_lost_recently", "group": "pet", "subgroup": "other", "label_ja": "最近ペットを亡くした",
     "base_rate": 0.01, "modifiers": {"age_band:senior": 1.3},
     "forces_boost": {"life_event_trigger": 0.2, "current_solution_frustration": 0.1}},
    {"id": "pet_rescue_adopt", "group": "pet", "subgroup": "other", "label_ja": "保護動物の里親",
     "base_rate": 0.015, "modifiers": {"age_band:middle": 1.2, "income_level:high": 1.2},
     "forces_boost": {"unmet_need_severity": 0.08, "aspirational_identity": 0.1}},
    {"id": "pet_premium_care", "group": "pet", "subgroup": "other", "label_ja": "ペットに高額支出する飼い主",
     "base_rate": 0.03, "modifiers": {"income_level:high": 2.0, "household_type:single": 1.3, "household_type:couple": 1.2},
     "forces_boost": {"perceived_value": 0.1, "financial_risk": -0.1}},
    {"id": "pet_travel_with", "group": "pet", "subgroup": "other", "label_ja": "ペットと旅行する飼い主",
     "base_rate": 0.02, "modifiers": {"income_level:high": 1.5, "household_type:couple": 1.3},
     "forces_boost": {"unmet_need_severity": 0.08}},

    # =========================================================================
    # GROUP: vehicle (~35 tags)
    # =========================================================================
    # --- subgroup: car_type ---
    {"id": "car_kei", "group": "vehicle", "subgroup": "car_type", "label_ja": "軽自動車所有",
     "base_rate": 0.20, "modifiers": {"region:kanto": 0.6, "region:kansai": 0.7, "region:tohoku": 1.4, "region:hokkaido": 1.3, "region:kyushu": 1.3, "income_level:low": 1.3},
     "forces_boost": {}},
    {"id": "car_compact", "group": "vehicle", "subgroup": "car_type", "label_ja": "コンパクトカー所有",
     "base_rate": 0.12, "modifiers": {"household_type:couple": 1.2, "household_type:family_young": 1.3, "region:kanto": 0.7},
     "forces_boost": {}},
    {"id": "car_sedan", "group": "vehicle", "subgroup": "car_type", "label_ja": "セダン所有",
     "base_rate": 0.06, "modifiers": {"age_band:senior": 1.3, "income_level:middle": 1.2},
     "forces_boost": {}},
    {"id": "car_suv", "group": "vehicle", "subgroup": "car_type", "label_ja": "SUV所有",
     "base_rate": 0.08, "modifiers": {"household_type:family_young": 1.4, "household_type:family_school": 1.4, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "car_minivan", "group": "vehicle", "subgroup": "car_type", "label_ja": "ミニバン所有",
     "base_rate": 0.10, "modifiers": {"household_type:family_young": 1.8, "household_type:family_school": 2.0, "household_type:single": 0.2},
     "forces_boost": {}},
    {"id": "car_wagon", "group": "vehicle", "subgroup": "car_type", "label_ja": "ステーションワゴン所有",
     "base_rate": 0.03, "modifiers": {"household_type:family_school": 1.4, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "car_sports", "group": "vehicle", "subgroup": "car_type", "label_ja": "スポーツカー所有",
     "base_rate": 0.01, "modifiers": {"gender:male": 2.0, "income_level:high": 2.0, "age_band:young": 1.3, "household_type:single": 1.5},
     "forces_boost": {"novelty_appeal": 0.1}},
    {"id": "car_luxury", "group": "vehicle", "subgroup": "car_type", "label_ja": "高級車所有",
     "base_rate": 0.02, "modifiers": {"income_level:high": 3.0, "age_band:senior": 1.3},
     "forces_boost": {"brand_trust": 0.1, "financial_risk": -0.1}},
    {"id": "car_classic", "group": "vehicle", "subgroup": "car_type", "label_ja": "旧車・クラシックカー愛好",
     "base_rate": 0.005, "modifiers": {"gender:male": 2.0, "age_band:senior": 1.5, "income_level:high": 1.5},
     "forces_boost": {"novelty_appeal": 0.1}},
    # --- subgroup: car_powertrain ---
    {"id": "car_ev", "group": "vehicle", "subgroup": "car_powertrain", "label_ja": "EV所有",
     "base_rate": 0.02, "modifiers": {"income_level:high": 2.0, "region:kanto": 1.2, "age_band:middle": 1.2},
     "forces_boost": {"novelty_appeal": 0.1, "aspirational_identity": 0.1}},
    {"id": "car_hybrid", "group": "vehicle", "subgroup": "car_powertrain", "label_ja": "ハイブリッド車所有",
     "base_rate": 0.12, "modifiers": {"income_level:middle": 1.2, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "car_phev", "group": "vehicle", "subgroup": "car_powertrain", "label_ja": "PHEV所有",
     "base_rate": 0.01, "modifiers": {"income_level:high": 1.8},
     "forces_boost": {}},
    # --- subgroup: car_usage ---
    {"id": "car_commute_daily", "group": "vehicle", "subgroup": "car_usage", "label_ja": "車通勤（毎日）",
     "base_rate": 0.15, "modifiers": {"region:kanto": 0.5, "region:tohoku": 1.5, "region:hokkaido": 1.5, "region:kyushu": 1.3},
     "forces_boost": {}},
    {"id": "car_weekend_only", "group": "vehicle", "subgroup": "car_usage", "label_ja": "週末ドライバー",
     "base_rate": 0.10, "modifiers": {"region:kanto": 1.3, "region:kansai": 1.2},
     "forces_boost": {}},
    {"id": "car_shopping_needed", "group": "vehicle", "subgroup": "car_usage", "label_ja": "買い物に車が必須",
     "base_rate": 0.12, "modifiers": {"region:tohoku": 1.5, "region:hokkaido": 1.5, "region:kyushu": 1.3, "region:kanto": 0.5},
     "forces_boost": {"unmet_need_severity": 0.05}},
    {"id": "car_lease_subscription", "group": "vehicle", "subgroup": "car_usage", "label_ja": "カーリース・サブスク利用",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.5, "household_type:single": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "car_sharing_user", "group": "vehicle", "subgroup": "car_usage", "label_ja": "カーシェア利用者",
     "base_rate": 0.03, "modifiers": {"region:kanto": 1.8, "region:kansai": 1.5, "age_band:young": 1.5, "household_type:single": 1.4},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "car_none_license", "group": "vehicle", "subgroup": "car_usage", "label_ja": "免許あり車なし",
     "base_rate": 0.10, "modifiers": {"region:kanto": 1.8, "region:kansai": 1.5, "age_band:young": 1.3, "household_type:single": 1.3},
     "forces_boost": {}},
    {"id": "car_none_no_license", "group": "vehicle", "subgroup": "car_usage", "label_ja": "免許なし",
     "base_rate": 0.08, "modifiers": {"region:kanto": 1.5, "age_band:young": 1.3, "gender:female": 1.1},
     "forces_boost": {}},
    # --- subgroup: motorcycle ---
    {"id": "motorcycle_scooter", "group": "vehicle", "subgroup": "motorcycle", "label_ja": "スクーター・原付所有",
     "base_rate": 0.05, "modifiers": {"gender:male": 1.3, "age_band:young": 1.4, "region:kyushu": 1.2},
     "forces_boost": {}},
    {"id": "motorcycle_mid", "group": "vehicle", "subgroup": "motorcycle", "label_ja": "中型バイク所有",
     "base_rate": 0.02, "modifiers": {"gender:male": 2.0, "age_band:young": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "motorcycle_large", "group": "vehicle", "subgroup": "motorcycle", "label_ja": "大型バイク所有",
     "base_rate": 0.01, "modifiers": {"gender:male": 2.5, "age_band:senior": 1.4, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "motorcycle_touring", "group": "vehicle", "subgroup": "motorcycle", "label_ja": "バイクツーリング愛好",
     "base_rate": 0.015, "modifiers": {"gender:male": 2.0, "age_band:middle": 1.3, "age_band:senior": 1.3},
     "forces_boost": {}},
    # --- subgroup: bicycle ---
    {"id": "bicycle_road", "group": "vehicle", "subgroup": "bicycle", "label_ja": "ロードバイク愛好",
     "base_rate": 0.03, "modifiers": {"gender:male": 1.5, "age_band:middle": 1.3, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "bicycle_ebike", "group": "vehicle", "subgroup": "bicycle", "label_ja": "電動アシスト自転車利用",
     "base_rate": 0.05, "modifiers": {"household_type:family_young": 1.8, "gender:female": 1.3, "region:kanto": 1.2},
     "forces_boost": {}},
    {"id": "bicycle_commuter", "group": "vehicle", "subgroup": "bicycle", "label_ja": "自転車通勤",
     "base_rate": 0.04, "modifiers": {"region:kanto": 1.3, "region:kansai": 1.3, "age_band:young": 1.3, "gender:male": 1.2},
     "forces_boost": {}},
    {"id": "bicycle_mama", "group": "vehicle", "subgroup": "bicycle", "label_ja": "ママチャリ利用",
     "base_rate": 0.12, "modifiers": {"household_type:family_young": 1.6, "household_type:family_school": 1.4, "gender:female": 1.3},
     "forces_boost": {}},
    # --- subgroup: public_transit ---
    {"id": "transit_train_daily", "group": "vehicle", "subgroup": "public_transit", "label_ja": "電車通勤（毎日）",
     "base_rate": 0.25, "modifiers": {"region:kanto": 1.5, "region:kansai": 1.3, "region:hokkaido": 0.5, "region:tohoku": 0.5},
     "forces_boost": {}},
    {"id": "transit_bus_regular", "group": "vehicle", "subgroup": "public_transit", "label_ja": "バス通勤・通学",
     "base_rate": 0.08, "modifiers": {"region:kanto": 0.8, "age_band:young": 1.2, "age_band:senior": 1.3},
     "forces_boost": {}},
    {"id": "transit_green_car", "group": "vehicle", "subgroup": "public_transit", "label_ja": "グリーン車・指定席常用",
     "base_rate": 0.03, "modifiers": {"income_level:high": 2.5, "age_band:senior": 1.3},
     "forces_boost": {"brand_trust": 0.05}},
    {"id": "transit_shinkansen_frequent", "group": "vehicle", "subgroup": "public_transit", "label_ja": "新幹線頻繁利用",
     "base_rate": 0.04, "modifiers": {"income_level:high": 1.5, "region:kanto": 1.2, "region:kansai": 1.2},
     "forces_boost": {}},
    {"id": "transit_taxi_frequent", "group": "vehicle", "subgroup": "public_transit", "label_ja": "タクシー頻繁利用",
     "base_rate": 0.03, "modifiers": {"income_level:high": 2.5, "region:kanto": 1.3, "age_band:senior": 1.3},
     "forces_boost": {"financial_risk": -0.05}},
    {"id": "transit_ride_hailing", "group": "vehicle", "subgroup": "public_transit", "label_ja": "ライドシェア利用",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.5, "region:kanto": 1.3, "income_level:high": 1.2},
     "forces_boost": {"novelty_appeal": 0.05}},

    # =========================================================================
    # GROUP: digital (~40 tags)
    # =========================================================================
    # --- subgroup: sns ---
    {"id": "sns_x_heavy", "group": "digital", "subgroup": "sns", "label_ja": "X (Twitter) ヘビーユーザー",
     "base_rate": 0.15, "modifiers": {"age_band:young": 1.5, "age_band:middle": 1.1, "age_band:senior": 0.5},
     "forces_boost": {"social_proof_strength": 0.1}},
    {"id": "sns_instagram", "group": "digital", "subgroup": "sns", "label_ja": "Instagram アクティブ",
     "base_rate": 0.20, "modifiers": {"age_band:young": 1.4, "gender:female": 1.3, "age_band:senior": 0.4},
     "forces_boost": {"social_proof_strength": 0.08, "aspirational_identity": 0.05}},
    {"id": "sns_tiktok", "group": "digital", "subgroup": "sns", "label_ja": "TikTok アクティブ",
     "base_rate": 0.12, "modifiers": {"age_band:young": 2.0, "age_band:middle": 0.6, "age_band:senior": 0.2},
     "forces_boost": {"social_proof_strength": 0.1, "novelty_appeal": 0.05}},
    {"id": "sns_youtube_viewer", "group": "digital", "subgroup": "sns", "label_ja": "YouTube ヘビー視聴者",
     "base_rate": 0.30, "modifiers": {"age_band:young": 1.3, "gender:male": 1.1},
     "forces_boost": {"social_proof_strength": 0.05}},
    {"id": "sns_youtube_creator", "group": "digital", "subgroup": "sns", "label_ja": "YouTube クリエイター",
     "base_rate": 0.01, "modifiers": {"age_band:young": 2.0, "gender:male": 1.3},
     "forces_boost": {"novelty_appeal": 0.1, "aspirational_identity": 0.1}},
    {"id": "sns_line_heavy", "group": "digital", "subgroup": "sns", "label_ja": "LINE ヘビーユーザー",
     "base_rate": 0.35, "modifiers": {"age_band:senior": 0.7},
     "forces_boost": {}},
    {"id": "sns_facebook", "group": "digital", "subgroup": "sns", "label_ja": "Facebook アクティブ",
     "base_rate": 0.08, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.2, "age_band:young": 0.4},
     "forces_boost": {}},
    {"id": "sns_threads", "group": "digital", "subgroup": "sns", "label_ja": "Threads 利用",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.5},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "sns_pinterest", "group": "digital", "subgroup": "sns", "label_ja": "Pinterest 利用",
     "base_rate": 0.04, "modifiers": {"gender:female": 1.8, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "sns_note_blogger", "group": "digital", "subgroup": "sns", "label_ja": "note/ブログ発信者",
     "base_rate": 0.03, "modifiers": {"age_band:middle": 1.3, "income_level:high": 1.2},
     "forces_boost": {"aspirational_identity": 0.08}},
    # --- subgroup: gaming ---
    {"id": "game_mobile_casual", "group": "digital", "subgroup": "gaming", "label_ja": "モバイルゲーム（カジュアル）",
     "base_rate": 0.25, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "game_mobile_gacha", "group": "digital", "subgroup": "gaming", "label_ja": "ガチャゲー課金者",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.4, "gender:male": 1.3, "age_band:middle": 1.1},
     "forces_boost": {"financial_risk": -0.05}},
    {"id": "game_console_nintendo", "group": "digital", "subgroup": "gaming", "label_ja": "Nintendo Switch ユーザー",
     "base_rate": 0.12, "modifiers": {"household_type:family_young": 1.5, "household_type:family_school": 1.6, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "game_console_ps", "group": "digital", "subgroup": "gaming", "label_ja": "PlayStation ユーザー",
     "base_rate": 0.06, "modifiers": {"gender:male": 1.6, "age_band:young": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "game_pc", "group": "digital", "subgroup": "gaming", "label_ja": "PCゲーマー",
     "base_rate": 0.05, "modifiers": {"gender:male": 1.8, "age_band:young": 1.4, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "game_esports", "group": "digital", "subgroup": "gaming", "label_ja": "eスポーツ観戦・参加",
     "base_rate": 0.02, "modifiers": {"gender:male": 1.8, "age_band:young": 2.0},
     "forces_boost": {"social_proof_strength": 0.05}},
    {"id": "game_vr", "group": "digital", "subgroup": "gaming", "label_ja": "VR/ARゲーマー",
     "base_rate": 0.015, "modifiers": {"gender:male": 1.5, "age_band:young": 1.5, "income_level:high": 1.5},
     "forces_boost": {"novelty_appeal": 0.1}},
    {"id": "game_board_tabletop", "group": "digital", "subgroup": "gaming", "label_ja": "ボードゲーム・TRPG愛好",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.2},
     "forces_boost": {}},
    # --- subgroup: streaming ---
    {"id": "stream_netflix", "group": "digital", "subgroup": "streaming", "label_ja": "Netflix 契約",
     "base_rate": 0.10, "modifiers": {"age_band:young": 1.3, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "stream_amazon_prime", "group": "digital", "subgroup": "streaming", "label_ja": "Amazon Prime Video 利用",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "stream_disney_plus", "group": "digital", "subgroup": "streaming", "label_ja": "Disney+ 契約",
     "base_rate": 0.04, "modifiers": {"household_type:family_young": 1.6, "household_type:family_school": 1.5},
     "forces_boost": {}},
    {"id": "stream_music_spotify", "group": "digital", "subgroup": "streaming", "label_ja": "Spotify/Apple Music 利用",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.5, "age_band:senior": 0.4},
     "forces_boost": {}},
    {"id": "stream_audiobook", "group": "digital", "subgroup": "streaming", "label_ja": "オーディオブック利用",
     "base_rate": 0.03, "modifiers": {"age_band:middle": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "stream_podcast", "group": "digital", "subgroup": "streaming", "label_ja": "ポッドキャスト定期聴取",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2, "income_level:high": 1.2},
     "forces_boost": {}},
    # --- subgroup: ecommerce ---
    {"id": "shop_amazon_heavy", "group": "digital", "subgroup": "ecommerce", "label_ja": "Amazon ヘビー利用",
     "base_rate": 0.20, "modifiers": {"age_band:middle": 1.1, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "shop_rakuten_heavy", "group": "digital", "subgroup": "ecommerce", "label_ja": "楽天経済圏ヘビー利用",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.2, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "shop_flea_mercari", "group": "digital", "subgroup": "ecommerce", "label_ja": "メルカリ アクティブ",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.4, "gender:female": 1.3},
     "forces_boost": {}},
    {"id": "shop_subscription_box", "group": "digital", "subgroup": "ecommerce", "label_ja": "サブスクボックス利用",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "gender:female": 1.3, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    # --- subgroup: device ---
    {"id": "device_iphone", "group": "digital", "subgroup": "device", "label_ja": "iPhone ユーザー",
     "base_rate": 0.45, "modifiers": {"age_band:young": 1.2, "income_level:high": 1.1},
     "forces_boost": {}},
    {"id": "device_android", "group": "digital", "subgroup": "device", "label_ja": "Android ユーザー",
     "base_rate": 0.50, "modifiers": {"age_band:senior": 1.1, "income_level:low": 1.1},
     "forces_boost": {}},
    {"id": "device_ipad_tablet", "group": "digital", "subgroup": "device", "label_ja": "タブレット所有",
     "base_rate": 0.15, "modifiers": {"income_level:high": 1.3, "household_type:family_school": 1.2},
     "forces_boost": {}},
    {"id": "device_smartwatch", "group": "digital", "subgroup": "device", "label_ja": "スマートウォッチ所有",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2, "income_level:high": 1.5},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "device_smart_speaker", "group": "digital", "subgroup": "device", "label_ja": "スマートスピーカー所有",
     "base_rate": 0.06, "modifiers": {"income_level:high": 1.4, "household_type:family_young": 1.2},
     "forces_boost": {}},
    {"id": "device_pc_heavy", "group": "digital", "subgroup": "device", "label_ja": "PC ヘビーユーザー",
     "base_rate": 0.20, "modifiers": {"gender:male": 1.3, "age_band:middle": 1.1, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "device_multi_screen", "group": "digital", "subgroup": "device", "label_ja": "マルチデバイス使い",
     "base_rate": 0.10, "modifiers": {"income_level:high": 1.5, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "tech_early_adopter", "group": "digital", "subgroup": "device", "label_ja": "新ガジェット好き",
     "base_rate": 0.05, "modifiers": {"gender:male": 1.5, "age_band:young": 1.4, "income_level:high": 1.8},
     "forces_boost": {"novelty_appeal": 0.15, "performance_uncertainty": -0.1}},
    {"id": "tech_ai_interested", "group": "digital", "subgroup": "device", "label_ja": "AI/ChatGPT 活用",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.2, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.1, "performance_uncertainty": -0.05}},

    # =========================================================================
    # GROUP: health (~35 tags)
    # =========================================================================
    # --- subgroup: fitness ---
    {"id": "fitness_gym_member", "group": "health", "subgroup": "fitness", "label_ja": "ジム会員",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.2, "income_level:high": 1.3, "region:kanto": 1.2},
     "forces_boost": {"perceived_value": 0.05}},
    {"id": "fitness_yoga", "group": "health", "subgroup": "fitness", "label_ja": "ヨガ実践者",
     "base_rate": 0.05, "modifiers": {"gender:female": 2.0, "age_band:middle": 1.3, "income_level:high": 1.2},
     "forces_boost": {"perceived_value": 0.05}},
    {"id": "fitness_runner", "group": "health", "subgroup": "fitness", "label_ja": "ランニング愛好",
     "base_rate": 0.07, "modifiers": {"gender:male": 1.2, "age_band:middle": 1.3, "age_band:young": 1.2},
     "forces_boost": {}},
    {"id": "fitness_swimmer", "group": "health", "subgroup": "fitness", "label_ja": "スイミング愛好",
     "base_rate": 0.04, "modifiers": {"age_band:senior": 1.3, "household_type:family_school": 1.2},
     "forces_boost": {}},
    {"id": "fitness_home_training", "group": "health", "subgroup": "fitness", "label_ja": "ホームトレーニング",
     "base_rate": 0.10, "modifiers": {"age_band:young": 1.3, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "fitness_personal_trainer", "group": "health", "subgroup": "fitness", "label_ja": "パーソナルトレーナー利用",
     "base_rate": 0.02, "modifiers": {"income_level:high": 2.5, "age_band:young": 1.3},
     "forces_boost": {"perceived_value": 0.1}},
    {"id": "fitness_martial_arts", "group": "health", "subgroup": "fitness", "label_ja": "格闘技・武道",
     "base_rate": 0.03, "modifiers": {"gender:male": 1.5, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "fitness_dance", "group": "health", "subgroup": "fitness", "label_ja": "ダンス・バレエ",
     "base_rate": 0.03, "modifiers": {"gender:female": 1.8, "age_band:young": 1.5},
     "forces_boost": {}},
    # --- subgroup: diet ---
    {"id": "diet_restricting", "group": "health", "subgroup": "diet", "label_ja": "ダイエット実践中",
     "base_rate": 0.12, "modifiers": {"gender:female": 1.3, "age_band:middle": 1.2},
     "forces_boost": {"current_solution_frustration": 0.08}},
    {"id": "diet_supplement_user", "group": "health", "subgroup": "diet", "label_ja": "サプリメント常用",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.2, "age_band:senior": 1.3, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "diet_protein_conscious", "group": "health", "subgroup": "diet", "label_ja": "プロテイン・たんぱく質重視",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.4, "gender:male": 1.3},
     "forces_boost": {}},
    {"id": "diet_low_carb", "group": "health", "subgroup": "diet", "label_ja": "糖質制限実践",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.2},
     "forces_boost": {}},
    {"id": "diet_fasting", "group": "health", "subgroup": "diet", "label_ja": "ファスティング実践",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.3, "gender:female": 1.2},
     "forces_boost": {}},
    # --- subgroup: medical ---
    {"id": "medical_allergy", "group": "health", "subgroup": "medical", "label_ja": "アレルギー持ち（花粉・食物等）",
     "base_rate": 0.25, "modifiers": {"age_band:young": 1.2},
     "forces_boost": {"unmet_need_severity": 0.05}},
    {"id": "medical_chronic", "group": "health", "subgroup": "medical", "label_ja": "慢性疾患あり",
     "base_rate": 0.10, "modifiers": {"age_band:senior": 1.8, "age_band:middle": 1.2},
     "forces_boost": {"unmet_need_severity": 0.1, "current_solution_frustration": 0.05}},
    {"id": "medical_regular_checkup", "group": "health", "subgroup": "medical", "label_ja": "定期健診受診",
     "base_rate": 0.30, "modifiers": {"age_band:middle": 1.2, "age_band:senior": 1.3, "income_level:high": 1.1},
     "forces_boost": {}},
    {"id": "medical_dental_regular", "group": "health", "subgroup": "medical", "label_ja": "歯科定期通院",
     "base_rate": 0.15, "modifiers": {"income_level:high": 1.3, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "medical_hospital_frequent", "group": "health", "subgroup": "medical", "label_ja": "通院頻度高い",
     "base_rate": 0.08, "modifiers": {"age_band:senior": 2.0},
     "forces_boost": {"unmet_need_severity": 0.1}},
    {"id": "medical_prescription_regular", "group": "health", "subgroup": "medical", "label_ja": "処方薬常用",
     "base_rate": 0.12, "modifiers": {"age_band:senior": 1.8, "age_band:middle": 1.1},
     "forces_boost": {}},
    # --- subgroup: mental ---
    {"id": "mental_stress_high", "group": "health", "subgroup": "mental", "label_ja": "ストレス高い",
     "base_rate": 0.20, "modifiers": {"age_band:middle": 1.3, "household_type:family_young": 1.2},
     "forces_boost": {"current_solution_frustration": 0.1, "unmet_need_severity": 0.08}},
    {"id": "mental_therapy_user", "group": "health", "subgroup": "mental", "label_ja": "カウンセリング利用",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "income_level:high": 1.3, "region:kanto": 1.2},
     "forces_boost": {"perceived_value": 0.08}},
    {"id": "mental_meditation", "group": "health", "subgroup": "mental", "label_ja": "瞑想・マインドフルネス実践",
     "base_rate": 0.04, "modifiers": {"age_band:middle": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "mental_sleep_issue", "group": "health", "subgroup": "mental", "label_ja": "睡眠に悩みがある",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.2},
     "forces_boost": {"current_solution_frustration": 0.1, "unmet_need_severity": 0.08}},
    # --- subgroup: habits ---
    {"id": "habit_smoker", "group": "health", "subgroup": "habits", "label_ja": "喫煙者",
     "base_rate": 0.15, "modifiers": {"gender:male": 1.5, "age_band:middle": 1.1, "income_level:low": 1.2},
     "forces_boost": {}},
    {"id": "habit_former_smoker", "group": "health", "subgroup": "habits", "label_ja": "禁煙成功者",
     "base_rate": 0.08, "modifiers": {"age_band:middle": 1.2, "age_band:senior": 1.3},
     "forces_boost": {}},
    {"id": "habit_heavy_drinker", "group": "health", "subgroup": "habits", "label_ja": "飲酒頻度高い",
     "base_rate": 0.12, "modifiers": {"gender:male": 1.5, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "habit_non_drinker", "group": "health", "subgroup": "habits", "label_ja": "飲酒しない",
     "base_rate": 0.20, "modifiers": {"gender:female": 1.2, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "habit_early_riser", "group": "health", "subgroup": "habits", "label_ja": "早起き習慣",
     "base_rate": 0.15, "modifiers": {"age_band:senior": 1.5, "household_type:family_young": 1.2},
     "forces_boost": {}},
    {"id": "habit_night_owl", "group": "health", "subgroup": "habits", "label_ja": "夜型生活",
     "base_rate": 0.15, "modifiers": {"age_band:young": 1.5, "household_type:single": 1.3},
     "forces_boost": {}},

    # =========================================================================
    # GROUP: food (~35 tags)
    # =========================================================================
    # --- subgroup: cooking ---
    {"id": "cook_daily", "group": "food", "subgroup": "cooking", "label_ja": "毎日自炊",
     "base_rate": 0.25, "modifiers": {"household_type:family_young": 1.3, "household_type:family_school": 1.3, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "cook_weekend", "group": "food", "subgroup": "cooking", "label_ja": "週末自炊",
     "base_rate": 0.15, "modifiers": {"household_type:single": 1.3, "household_type:couple": 1.3, "age_band:young": 1.2},
     "forces_boost": {}},
    {"id": "cook_rarely", "group": "food", "subgroup": "cooking", "label_ja": "ほぼ自炊しない",
     "base_rate": 0.15, "modifiers": {"household_type:single": 1.5, "gender:male": 1.3, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "cook_baking", "group": "food", "subgroup": "cooking", "label_ja": "お菓子・パン作り趣味",
     "base_rate": 0.06, "modifiers": {"gender:female": 1.8, "household_type:family_young": 1.3},
     "forces_boost": {}},
    {"id": "cook_fermentation", "group": "food", "subgroup": "cooking", "label_ja": "発酵食品手作り",
     "base_rate": 0.04, "modifiers": {"age_band:middle": 1.3, "gender:female": 1.4},
     "forces_boost": {}},
    {"id": "cook_meal_prep", "group": "food", "subgroup": "cooking", "label_ja": "作り置き習慣",
     "base_rate": 0.10, "modifiers": {"household_type:family_young": 1.4, "household_type:family_school": 1.3, "gender:female": 1.2},
     "forces_boost": {}},
    # --- subgroup: dining ---
    {"id": "dine_out_weekly", "group": "food", "subgroup": "dining", "label_ja": "外食（週1以上）",
     "base_rate": 0.20, "modifiers": {"household_type:single": 1.3, "household_type:couple": 1.2, "income_level:high": 1.3, "age_band:young": 1.2},
     "forces_boost": {}},
    {"id": "dine_out_daily", "group": "food", "subgroup": "dining", "label_ja": "外食（ほぼ毎日）",
     "base_rate": 0.08, "modifiers": {"household_type:single": 1.8, "gender:male": 1.3, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "dine_fine_dining", "group": "food", "subgroup": "dining", "label_ja": "高級レストラン好き",
     "base_rate": 0.03, "modifiers": {"income_level:high": 3.0, "age_band:middle": 1.2},
     "forces_boost": {"brand_trust": 0.05}},
    {"id": "dine_ramen_enthusiast", "group": "food", "subgroup": "dining", "label_ja": "ラーメン好き",
     "base_rate": 0.12, "modifiers": {"gender:male": 1.4, "age_band:young": 1.3},
     "forces_boost": {}},
    {"id": "dine_cafe_frequent", "group": "food", "subgroup": "dining", "label_ja": "カフェ頻繁利用",
     "base_rate": 0.10, "modifiers": {"gender:female": 1.3, "age_band:young": 1.4, "region:kanto": 1.2},
     "forces_boost": {}},
    {"id": "dine_izakaya_frequent", "group": "food", "subgroup": "dining", "label_ja": "居酒屋頻繁利用",
     "base_rate": 0.12, "modifiers": {"gender:male": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "dine_food_court", "group": "food", "subgroup": "dining", "label_ja": "フードコート頻繁利用",
     "base_rate": 0.10, "modifiers": {"household_type:family_young": 1.5, "household_type:family_school": 1.4},
     "forces_boost": {}},
    # --- subgroup: delivery ---
    {"id": "food_delivery_regular", "group": "food", "subgroup": "delivery", "label_ja": "フードデリバリー定期利用",
     "base_rate": 0.08, "modifiers": {"region:kanto": 1.5, "region:kansai": 1.3, "age_band:young": 1.4, "household_type:single": 1.3},
     "forces_boost": {}},
    {"id": "food_meal_kit", "group": "food", "subgroup": "delivery", "label_ja": "ミールキット利用",
     "base_rate": 0.03, "modifiers": {"household_type:family_young": 1.5, "household_type:couple": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "food_convenience_store", "group": "food", "subgroup": "delivery", "label_ja": "コンビニ飯中心",
     "base_rate": 0.15, "modifiers": {"household_type:single": 1.5, "gender:male": 1.3, "age_band:young": 1.4},
     "forces_boost": {}},
    {"id": "food_frozen_regular", "group": "food", "subgroup": "delivery", "label_ja": "冷凍食品ヘビー利用",
     "base_rate": 0.12, "modifiers": {"household_type:single": 1.3, "age_band:middle": 1.1},
     "forces_boost": {}},
    # --- subgroup: preference ---
    {"id": "food_organic", "group": "food", "subgroup": "preference", "label_ja": "オーガニック食品志向",
     "base_rate": 0.06, "modifiers": {"gender:female": 1.4, "income_level:high": 1.5, "household_type:family_young": 1.3},
     "forces_boost": {"perceived_value": 0.05}},
    {"id": "food_vegan", "group": "food", "subgroup": "preference", "label_ja": "ヴィーガン",
     "base_rate": 0.01, "modifiers": {"age_band:young": 1.5, "gender:female": 1.3},
     "forces_boost": {"aspirational_identity": 0.1}},
    {"id": "food_vegetarian", "group": "food", "subgroup": "preference", "label_ja": "ベジタリアン",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.3, "gender:female": 1.3},
     "forces_boost": {}},
    {"id": "food_gluten_free", "group": "food", "subgroup": "preference", "label_ja": "グルテンフリー志向",
     "base_rate": 0.02, "modifiers": {"gender:female": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "food_halal_kosher", "group": "food", "subgroup": "preference", "label_ja": "ハラール・コーシャ対応",
     "base_rate": 0.005, "modifiers": {},
     "forces_boost": {"unmet_need_severity": 0.1}},
    {"id": "food_local_produce", "group": "food", "subgroup": "preference", "label_ja": "地産地消志向",
     "base_rate": 0.08, "modifiers": {"age_band:senior": 1.3, "region:tohoku": 1.3, "region:hokkaido": 1.3},
     "forces_boost": {}},
    # --- subgroup: beverage ---
    {"id": "bev_coffee_enthusiast", "group": "food", "subgroup": "beverage", "label_ja": "コーヒー愛好家",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.2, "gender:male": 1.1},
     "forces_boost": {}},
    {"id": "bev_tea_enthusiast", "group": "food", "subgroup": "beverage", "label_ja": "日本茶・中国茶愛好",
     "base_rate": 0.08, "modifiers": {"age_band:senior": 1.4, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "bev_craft_beer", "group": "food", "subgroup": "beverage", "label_ja": "クラフトビール愛好",
     "base_rate": 0.04, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2, "gender:male": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "bev_wine_lover", "group": "food", "subgroup": "beverage", "label_ja": "ワイン愛好",
     "base_rate": 0.05, "modifiers": {"income_level:high": 1.8, "age_band:middle": 1.2, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "bev_whisky_spirits", "group": "food", "subgroup": "beverage", "label_ja": "ウイスキー・蒸留酒愛好",
     "base_rate": 0.04, "modifiers": {"gender:male": 1.5, "age_band:middle": 1.2, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "bev_sake_enthusiast", "group": "food", "subgroup": "beverage", "label_ja": "日本酒愛好",
     "base_rate": 0.05, "modifiers": {"gender:male": 1.3, "age_band:middle": 1.2, "age_band:senior": 1.3},
     "forces_boost": {}},

    # =========================================================================
    # GROUP: finance (~35 tags)
    # =========================================================================
    # --- subgroup: investment ---
    {"id": "fin_stock_active", "group": "finance", "subgroup": "investment", "label_ja": "個別株投資（アクティブ）",
     "base_rate": 0.08, "modifiers": {"gender:male": 1.4, "age_band:middle": 1.3, "income_level:high": 1.5},
     "forces_boost": {"perceived_value": 0.05}},
    {"id": "fin_fund_investor", "group": "finance", "subgroup": "investment", "label_ja": "投資信託保有",
     "base_rate": 0.12, "modifiers": {"age_band:middle": 1.2, "income_level:high": 1.4},
     "forces_boost": {}},
    {"id": "fin_nisa_user", "group": "finance", "subgroup": "investment", "label_ja": "NISA 利用",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.2, "income_level:high": 1.3, "age_band:young": 1.1},
     "forces_boost": {}},
    {"id": "fin_ideco_user", "group": "finance", "subgroup": "investment", "label_ja": "iDeCo 利用",
     "base_rate": 0.06, "modifiers": {"age_band:middle": 1.4, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "fin_crypto_active", "group": "finance", "subgroup": "investment", "label_ja": "暗号資産トレーダー",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.8, "gender:male": 1.5},
     "forces_boost": {"novelty_appeal": 0.1, "financial_risk": -0.1}},
    {"id": "fin_crypto_holder", "group": "finance", "subgroup": "investment", "label_ja": "暗号資産保有（長期）",
     "base_rate": 0.05, "modifiers": {"age_band:young": 1.5, "gender:male": 1.4, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "fin_real_estate_investor", "group": "finance", "subgroup": "investment", "label_ja": "不動産投資家",
     "base_rate": 0.02, "modifiers": {"income_level:high": 3.0, "age_band:middle": 1.3, "age_band:senior": 1.2},
     "forces_boost": {"perceived_value": 0.08}},
    {"id": "fin_fx_trader", "group": "finance", "subgroup": "investment", "label_ja": "FXトレーダー",
     "base_rate": 0.02, "modifiers": {"gender:male": 1.5, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "fin_robo_advisor", "group": "finance", "subgroup": "investment", "label_ja": "ロボアドバイザー利用",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    # --- subgroup: saving ---
    {"id": "fin_budget_strict", "group": "finance", "subgroup": "saving", "label_ja": "家計簿厳密管理",
     "base_rate": 0.10, "modifiers": {"gender:female": 1.3, "household_type:family_young": 1.3, "household_type:family_school": 1.2},
     "forces_boost": {}},
    {"id": "fin_savings_goal", "group": "finance", "subgroup": "saving", "label_ja": "貯蓄目標あり",
     "base_rate": 0.15, "modifiers": {"age_band:young": 1.2, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "fin_point_collector", "group": "finance", "subgroup": "saving", "label_ja": "ポイ活・ポイント収集",
     "base_rate": 0.20, "modifiers": {"gender:female": 1.3, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "fin_coupon_hunter", "group": "finance", "subgroup": "saving", "label_ja": "クーポン積極活用",
     "base_rate": 0.15, "modifiers": {"gender:female": 1.2, "income_level:low": 1.3},
     "forces_boost": {}},
    {"id": "fin_frugal", "group": "finance", "subgroup": "saving", "label_ja": "節約志向",
     "base_rate": 0.20, "modifiers": {"income_level:low": 1.4, "household_type:family_young": 1.2},
     "forces_boost": {"financial_risk": 0.1}},
    # --- subgroup: insurance ---
    {"id": "fin_insurance_life", "group": "finance", "subgroup": "insurance", "label_ja": "生命保険加入",
     "base_rate": 0.40, "modifiers": {"age_band:middle": 1.2, "household_type:family_young": 1.3, "household_type:family_school": 1.3},
     "forces_boost": {}},
    {"id": "fin_insurance_medical", "group": "finance", "subgroup": "insurance", "label_ja": "医療保険加入",
     "base_rate": 0.35, "modifiers": {"age_band:middle": 1.2, "age_band:senior": 1.1},
     "forces_boost": {}},
    {"id": "fin_insurance_car", "group": "finance", "subgroup": "insurance", "label_ja": "自動車保険加入",
     "base_rate": 0.30, "modifiers": {"region:tohoku": 1.3, "region:hokkaido": 1.3, "region:kanto": 0.7},
     "forces_boost": {}},
    {"id": "fin_insurance_pet", "group": "finance", "subgroup": "insurance", "label_ja": "ペット保険加入",
     "base_rate": 0.04, "modifiers": {"income_level:high": 1.5},
     "forces_boost": {}},
    {"id": "fin_insurance_reviewing", "group": "finance", "subgroup": "insurance", "label_ja": "保険見直し検討中",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.3, "household_type:family_young": 1.3},
     "forces_boost": {"current_solution_frustration": 0.1}},
    # --- subgroup: payment ---
    {"id": "fin_cashless_heavy", "group": "finance", "subgroup": "payment", "label_ja": "キャッシュレス決済メイン",
     "base_rate": 0.25, "modifiers": {"age_band:young": 1.3, "region:kanto": 1.2, "income_level:high": 1.1},
     "forces_boost": {}},
    {"id": "fin_credit_premium", "group": "finance", "subgroup": "payment", "label_ja": "プレミアムクレジットカード",
     "base_rate": 0.05, "modifiers": {"income_level:high": 3.0, "age_band:middle": 1.2},
     "forces_boost": {"brand_trust": 0.05}},
    {"id": "fin_qr_pay", "group": "finance", "subgroup": "payment", "label_ja": "QR決済メイン（PayPay等）",
     "base_rate": 0.20, "modifiers": {"age_band:young": 1.2, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "fin_cash_preference", "group": "finance", "subgroup": "payment", "label_ja": "現金主義",
     "base_rate": 0.15, "modifiers": {"age_band:senior": 1.5, "income_level:low": 1.2},
     "forces_boost": {"behavioral_automaticity": 0.05}},
    {"id": "fin_fintech_user", "group": "finance", "subgroup": "payment", "label_ja": "FinTechサービス利用",
     "base_rate": 0.05, "modifiers": {"age_band:young": 1.5, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "fin_tax_optimizer", "group": "finance", "subgroup": "payment", "label_ja": "確定申告・節税積極的",
     "base_rate": 0.08, "modifiers": {"age_band:middle": 1.3, "income_level:high": 1.5},
     "forces_boost": {}},

    # =========================================================================
    # GROUP: housing (~30 tags)
    # =========================================================================
    # --- subgroup: ownership ---
    {"id": "housing_own_house", "group": "housing", "subgroup": "ownership", "label_ja": "戸建て所有",
     "base_rate": 0.25, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.4, "household_type:family_school": 1.4, "region:kanto": 0.8},
     "forces_boost": {}},
    {"id": "housing_own_mansion", "group": "housing", "subgroup": "ownership", "label_ja": "分譲マンション所有",
     "base_rate": 0.15, "modifiers": {"region:kanto": 1.5, "region:kansai": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "housing_rent_apartment", "group": "housing", "subgroup": "ownership", "label_ja": "賃貸アパート",
     "base_rate": 0.20, "modifiers": {"age_band:young": 1.5, "household_type:single": 1.4, "income_level:low": 1.2},
     "forces_boost": {}},
    {"id": "housing_rent_mansion", "group": "housing", "subgroup": "ownership", "label_ja": "賃貸マンション",
     "base_rate": 0.12, "modifiers": {"region:kanto": 1.4, "age_band:young": 1.2, "income_level:middle": 1.2},
     "forces_boost": {}},
    {"id": "housing_share_house", "group": "housing", "subgroup": "ownership", "label_ja": "シェアハウス居住",
     "base_rate": 0.015, "modifiers": {"age_band:young": 3.0, "household_type:single": 2.0, "region:kanto": 1.5},
     "forces_boost": {"social_proof_strength": 0.05}},
    {"id": "housing_public", "group": "housing", "subgroup": "ownership", "label_ja": "公営住宅",
     "base_rate": 0.04, "modifiers": {"income_level:low": 2.0, "age_band:senior": 1.3},
     "forces_boost": {}},
    {"id": "housing_parents", "group": "housing", "subgroup": "ownership", "label_ja": "実家暮らし",
     "base_rate": 0.12, "modifiers": {"age_band:young": 2.0, "household_type:single": 1.3},
     "forces_boost": {}},
    # --- subgroup: style ---
    {"id": "housing_renovation_diy", "group": "housing", "subgroup": "style", "label_ja": "DIYリノベーション好き",
     "base_rate": 0.04, "modifiers": {"gender:male": 1.3, "age_band:middle": 1.3, "income_level:high": 1.2},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "housing_smart_home", "group": "housing", "subgroup": "style", "label_ja": "スマートホーム導入",
     "base_rate": 0.03, "modifiers": {"income_level:high": 2.0, "age_band:middle": 1.2},
     "forces_boost": {"novelty_appeal": 0.1}},
    {"id": "housing_garden_balcony", "group": "housing", "subgroup": "style", "label_ja": "ガーデニング・ベランダ菜園",
     "base_rate": 0.08, "modifiers": {"gender:female": 1.3, "age_band:senior": 1.4, "household_type:couple": 1.2},
     "forces_boost": {}},
    {"id": "housing_interior_enthusiast", "group": "housing", "subgroup": "style", "label_ja": "インテリアこだわり",
     "base_rate": 0.06, "modifiers": {"gender:female": 1.3, "income_level:high": 1.3, "age_band:young": 1.2},
     "forces_boost": {"perceived_value": 0.05}},
    {"id": "housing_minimalist_room", "group": "housing", "subgroup": "style", "label_ja": "ミニマリスト部屋",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "household_type:single": 1.5},
     "forces_boost": {"aspirational_identity": 0.05}},
    # --- subgroup: area ---
    {"id": "housing_urban_center", "group": "housing", "subgroup": "area", "label_ja": "都心居住",
     "base_rate": 0.08, "modifiers": {"region:kanto": 1.8, "region:kansai": 1.5, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "housing_suburban", "group": "housing", "subgroup": "area", "label_ja": "郊外居住",
     "base_rate": 0.30, "modifiers": {"household_type:family_young": 1.3, "household_type:family_school": 1.3},
     "forces_boost": {}},
    {"id": "housing_rural", "group": "housing", "subgroup": "area", "label_ja": "地方・田舎居住",
     "base_rate": 0.15, "modifiers": {"region:tohoku": 1.5, "region:hokkaido": 1.5, "region:shikoku": 1.4, "region:chugoku": 1.3},
     "forces_boost": {}},
    {"id": "housing_moving_planned", "group": "housing", "subgroup": "area", "label_ja": "引っ越し予定あり",
     "base_rate": 0.04, "modifiers": {"age_band:young": 1.5, "household_type:single": 1.3},
     "forces_boost": {"life_event_trigger": 0.15}},
    {"id": "housing_dual_residence", "group": "housing", "subgroup": "area", "label_ja": "二拠点生活",
     "base_rate": 0.01, "modifiers": {"income_level:high": 3.0, "age_band:senior": 1.3},
     "forces_boost": {}},
    # --- subgroup: home ---
    {"id": "housing_solar_panel", "group": "housing", "subgroup": "home", "label_ja": "太陽光パネル設置",
     "base_rate": 0.06, "modifiers": {"income_level:high": 1.5, "age_band:middle": 1.2, "region:kyushu": 1.3},
     "forces_boost": {}},
    {"id": "housing_ev_charging", "group": "housing", "subgroup": "home", "label_ja": "EV充電設備あり",
     "base_rate": 0.01, "modifiers": {"income_level:high": 3.0},
     "forces_boost": {}},
    {"id": "housing_storage_issue", "group": "housing", "subgroup": "home", "label_ja": "収納不足に悩む",
     "base_rate": 0.15, "modifiers": {"region:kanto": 1.3, "household_type:family_young": 1.3},
     "forces_boost": {"current_solution_frustration": 0.08}},
    {"id": "housing_noise_issue", "group": "housing", "subgroup": "home", "label_ja": "騒音問題あり",
     "base_rate": 0.08, "modifiers": {"region:kanto": 1.3, "household_type:family_young": 1.2},
     "forces_boost": {"current_solution_frustration": 0.1}},
    {"id": "housing_pest_concern", "group": "housing", "subgroup": "home", "label_ja": "害虫・害獣問題",
     "base_rate": 0.06, "modifiers": {"region:kyushu": 1.3, "region:kansai": 1.1},
     "forces_boost": {"current_solution_frustration": 0.08}},
    {"id": "housing_security_conscious", "group": "housing", "subgroup": "home", "label_ja": "防犯意識高い",
     "base_rate": 0.10, "modifiers": {"household_type:family_young": 1.3, "household_type:elderly": 1.3, "gender:female": 1.2},
     "forces_boost": {"unmet_need_severity": 0.05}},

    # =========================================================================
    # GROUP: hobby (~45 tags)
    # =========================================================================
    # --- subgroup: travel ---
    {"id": "hobby_travel_domestic", "group": "hobby", "subgroup": "travel", "label_ja": "国内旅行好き（年3回以上）",
     "base_rate": 0.12, "modifiers": {"income_level:high": 1.4, "age_band:senior": 1.2, "household_type:couple": 1.3},
     "forces_boost": {}},
    {"id": "hobby_travel_overseas", "group": "hobby", "subgroup": "travel", "label_ja": "海外旅行好き（年1回以上）",
     "base_rate": 0.06, "modifiers": {"income_level:high": 2.0, "age_band:young": 1.2, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "hobby_travel_backpacker", "group": "hobby", "subgroup": "travel", "label_ja": "バックパッカー",
     "base_rate": 0.02, "modifiers": {"age_band:young": 2.5, "household_type:single": 1.5},
     "forces_boost": {"novelty_appeal": 0.1}},
    {"id": "hobby_travel_luxury", "group": "hobby", "subgroup": "travel", "label_ja": "高級旅行志向",
     "base_rate": 0.03, "modifiers": {"income_level:high": 3.0, "age_band:senior": 1.3},
     "forces_boost": {"brand_trust": 0.05}},
    {"id": "hobby_travel_onsen", "group": "hobby", "subgroup": "travel", "label_ja": "温泉巡り好き",
     "base_rate": 0.10, "modifiers": {"age_band:senior": 1.4, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "hobby_travel_theme_park", "group": "hobby", "subgroup": "travel", "label_ja": "テーマパーク好き",
     "base_rate": 0.08, "modifiers": {"household_type:family_young": 1.5, "household_type:family_school": 1.5, "age_band:young": 1.3},
     "forces_boost": {}},
    # --- subgroup: outdoor ---
    {"id": "hobby_camping", "group": "hobby", "subgroup": "outdoor", "label_ja": "キャンプ愛好",
     "base_rate": 0.06, "modifiers": {"gender:male": 1.3, "household_type:family_young": 1.4, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "hobby_hiking", "group": "hobby", "subgroup": "outdoor", "label_ja": "登山・ハイキング",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.2, "gender:male": 1.1},
     "forces_boost": {}},
    {"id": "hobby_fishing", "group": "hobby", "subgroup": "outdoor", "label_ja": "釣り愛好",
     "base_rate": 0.05, "modifiers": {"gender:male": 2.0, "age_band:senior": 1.3, "region:hokkaido": 1.3},
     "forces_boost": {}},
    {"id": "hobby_surfing", "group": "hobby", "subgroup": "outdoor", "label_ja": "サーフィン",
     "base_rate": 0.015, "modifiers": {"age_band:young": 1.5, "gender:male": 1.5, "region:kanto": 1.2},
     "forces_boost": {}},
    {"id": "hobby_skiing", "group": "hobby", "subgroup": "outdoor", "label_ja": "スキー・スノーボード",
     "base_rate": 0.05, "modifiers": {"age_band:young": 1.3, "region:hokkaido": 1.5, "region:tohoku": 1.3, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "hobby_golf", "group": "hobby", "subgroup": "outdoor", "label_ja": "ゴルフ",
     "base_rate": 0.06, "modifiers": {"gender:male": 1.8, "age_band:middle": 1.3, "age_band:senior": 1.3, "income_level:high": 1.5},
     "forces_boost": {}},
    {"id": "hobby_tennis", "group": "hobby", "subgroup": "outdoor", "label_ja": "テニス",
     "base_rate": 0.03, "modifiers": {"income_level:high": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "hobby_baseball_softball", "group": "hobby", "subgroup": "outdoor", "label_ja": "野球・ソフトボール",
     "base_rate": 0.04, "modifiers": {"gender:male": 1.8, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "hobby_soccer_futsal", "group": "hobby", "subgroup": "outdoor", "label_ja": "サッカー・フットサル",
     "base_rate": 0.04, "modifiers": {"gender:male": 1.6, "age_band:young": 1.4},
     "forces_boost": {}},
    {"id": "hobby_gardening", "group": "hobby", "subgroup": "outdoor", "label_ja": "本格的ガーデニング",
     "base_rate": 0.05, "modifiers": {"age_band:senior": 1.5, "gender:female": 1.2},
     "forces_boost": {}},
    # --- subgroup: indoor ---
    {"id": "hobby_reading_heavy", "group": "hobby", "subgroup": "indoor", "label_ja": "読書好き（月5冊以上）",
     "base_rate": 0.05, "modifiers": {"income_level:high": 1.3, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "hobby_reading_kindle", "group": "hobby", "subgroup": "indoor", "label_ja": "電子書籍中心",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "hobby_movie_theater", "group": "hobby", "subgroup": "indoor", "label_ja": "映画館に月1以上",
     "base_rate": 0.05, "modifiers": {"age_band:young": 1.3, "household_type:couple": 1.2, "region:kanto": 1.2},
     "forces_boost": {}},
    {"id": "hobby_board_game", "group": "hobby", "subgroup": "indoor", "label_ja": "ボードゲーム愛好",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "hobby_puzzle_brain", "group": "hobby", "subgroup": "indoor", "label_ja": "パズル・脳トレ好き",
     "base_rate": 0.06, "modifiers": {"age_band:senior": 1.4},
     "forces_boost": {}},
    {"id": "hobby_cooking_gourmet", "group": "hobby", "subgroup": "indoor", "label_ja": "料理（趣味レベル）",
     "base_rate": 0.06, "modifiers": {"gender:male": 1.2, "age_band:middle": 1.2, "income_level:high": 1.2},
     "forces_boost": {}},
    # --- subgroup: culture ---
    {"id": "hobby_anime_fan", "group": "hobby", "subgroup": "culture", "label_ja": "アニメファン",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.5, "gender:male": 1.2},
     "forces_boost": {}},
    {"id": "hobby_manga_reader", "group": "hobby", "subgroup": "culture", "label_ja": "漫画愛読者",
     "base_rate": 0.15, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "hobby_cosplay", "group": "hobby", "subgroup": "culture", "label_ja": "コスプレ愛好",
     "base_rate": 0.01, "modifiers": {"age_band:young": 2.5, "gender:female": 1.3},
     "forces_boost": {"aspirational_identity": 0.1}},
    {"id": "hobby_figure_collector", "group": "hobby", "subgroup": "culture", "label_ja": "フィギュア・グッズ収集",
     "base_rate": 0.04, "modifiers": {"age_band:young": 1.4, "gender:male": 1.5},
     "forces_boost": {}},
    {"id": "hobby_idol_fan", "group": "hobby", "subgroup": "culture", "label_ja": "アイドル・推し活",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.5, "gender:female": 1.3},
     "forces_boost": {"aspirational_identity": 0.08}},
    {"id": "hobby_live_concert", "group": "hobby", "subgroup": "culture", "label_ja": "ライブ・コンサート頻繁参加",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.5, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "hobby_music_instrument", "group": "hobby", "subgroup": "culture", "label_ja": "楽器演奏",
     "base_rate": 0.05, "modifiers": {"age_band:young": 1.2, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "hobby_art_gallery", "group": "hobby", "subgroup": "culture", "label_ja": "美術館・展覧会好き",
     "base_rate": 0.04, "modifiers": {"income_level:high": 1.5, "age_band:senior": 1.2, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "hobby_theater_kabuki", "group": "hobby", "subgroup": "culture", "label_ja": "演劇・歌舞伎観劇",
     "base_rate": 0.03, "modifiers": {"age_band:senior": 1.4, "income_level:high": 1.5, "gender:female": 1.3},
     "forces_boost": {}},
    {"id": "hobby_shrine_temple", "group": "hobby", "subgroup": "culture", "label_ja": "神社仏閣巡り",
     "base_rate": 0.05, "modifiers": {"age_band:senior": 1.5, "gender:female": 1.2},
     "forces_boost": {}},
    # --- subgroup: creative ---
    {"id": "hobby_photography", "group": "hobby", "subgroup": "creative", "label_ja": "写真（一眼カメラ）",
     "base_rate": 0.04, "modifiers": {"gender:male": 1.3, "age_band:senior": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "hobby_illustration", "group": "hobby", "subgroup": "creative", "label_ja": "イラスト・絵描き",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.8, "gender:female": 1.3},
     "forces_boost": {}},
    {"id": "hobby_handcraft", "group": "hobby", "subgroup": "creative", "label_ja": "手芸・ハンドメイド",
     "base_rate": 0.05, "modifiers": {"gender:female": 2.0, "age_band:middle": 1.2, "age_band:senior": 1.2},
     "forces_boost": {}},
    {"id": "hobby_diy_woodwork", "group": "hobby", "subgroup": "creative", "label_ja": "DIY・木工",
     "base_rate": 0.03, "modifiers": {"gender:male": 1.8, "age_band:middle": 1.3, "age_band:senior": 1.2},
     "forces_boost": {}},
    {"id": "hobby_calligraphy", "group": "hobby", "subgroup": "creative", "label_ja": "書道・ペン字",
     "base_rate": 0.03, "modifiers": {"gender:female": 1.3, "age_band:senior": 1.4},
     "forces_boost": {}},

    # =========================================================================
    # GROUP: work_style (~30 tags)
    # =========================================================================
    # --- subgroup: employment ---
    {"id": "work_fulltime_large", "group": "work_style", "subgroup": "employment", "label_ja": "大企業正社員",
     "base_rate": 0.12, "modifiers": {"age_band:middle": 1.3, "region:kanto": 1.3, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "work_fulltime_sme", "group": "work_style", "subgroup": "employment", "label_ja": "中小企業正社員",
     "base_rate": 0.20, "modifiers": {"age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "work_civil_servant", "group": "work_style", "subgroup": "employment", "label_ja": "公務員",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.2},
     "forces_boost": {"behavioral_automaticity": 0.05}},
    {"id": "work_contract", "group": "work_style", "subgroup": "employment", "label_ja": "契約・派遣社員",
     "base_rate": 0.08, "modifiers": {"gender:female": 1.2, "age_band:young": 1.2},
     "forces_boost": {}},
    {"id": "work_part_time", "group": "work_style", "subgroup": "employment", "label_ja": "パート・アルバイト",
     "base_rate": 0.10, "modifiers": {"gender:female": 1.3, "age_band:young": 1.3, "income_level:low": 1.3},
     "forces_boost": {}},
    {"id": "work_freelance_engineer", "group": "work_style", "subgroup": "employment", "label_ja": "フリーランスエンジニア",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.3, "gender:male": 1.3, "region:kanto": 1.3},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "work_freelance_creative", "group": "work_style", "subgroup": "employment", "label_ja": "フリーランスクリエイティブ",
     "base_rate": 0.015, "modifiers": {"age_band:young": 1.3, "gender:female": 1.2},
     "forces_boost": {}},
    {"id": "work_self_employed", "group": "work_style", "subgroup": "employment", "label_ja": "自営業・個人事業主",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.2},
     "forces_boost": {}},
    {"id": "work_executive", "group": "work_style", "subgroup": "employment", "label_ja": "経営者・役員",
     "base_rate": 0.02, "modifiers": {"age_band:senior": 1.5, "income_level:high": 2.5, "gender:male": 1.3},
     "forces_boost": {"perceived_value": 0.05}},
    # --- subgroup: commute ---
    {"id": "work_remote_full", "group": "work_style", "subgroup": "commute", "label_ja": "フルリモートワーク",
     "base_rate": 0.05, "modifiers": {"region:kanto": 1.3, "income_level:high": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "work_remote_hybrid", "group": "work_style", "subgroup": "commute", "label_ja": "ハイブリッドワーク",
     "base_rate": 0.08, "modifiers": {"region:kanto": 1.4, "income_level:high": 1.2},
     "forces_boost": {}},
    {"id": "work_commute_long", "group": "work_style", "subgroup": "commute", "label_ja": "長距離通勤（1時間以上）",
     "base_rate": 0.10, "modifiers": {"region:kanto": 1.5, "household_type:family_school": 1.2},
     "forces_boost": {"current_solution_frustration": 0.05}},
    {"id": "work_commute_short", "group": "work_style", "subgroup": "commute", "label_ja": "近距離通勤（30分未満）",
     "base_rate": 0.15, "modifiers": {"region:hokkaido": 1.3, "region:tohoku": 1.3},
     "forces_boost": {}},
    # --- subgroup: style ---
    {"id": "work_overtime_heavy", "group": "work_style", "subgroup": "style", "label_ja": "残業多い",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.2, "age_band:middle": 1.3, "gender:male": 1.2},
     "forces_boost": {"current_solution_frustration": 0.05, "effort_risk": 0.05}},
    {"id": "work_shift_worker", "group": "work_style", "subgroup": "style", "label_ja": "シフト勤務",
     "base_rate": 0.08, "modifiers": {"income_level:low": 1.2},
     "forces_boost": {}},
    {"id": "work_night_shift", "group": "work_style", "subgroup": "style", "label_ja": "夜勤あり",
     "base_rate": 0.04, "modifiers": {"gender:male": 1.3},
     "forces_boost": {"current_solution_frustration": 0.05}},
    {"id": "work_wlb_priority", "group": "work_style", "subgroup": "style", "label_ja": "ワークライフバランス重視",
     "base_rate": 0.15, "modifiers": {"age_band:young": 1.3, "household_type:family_young": 1.3},
     "forces_boost": {}},
    # --- subgroup: aspiration ---
    {"id": "work_side_job", "group": "work_style", "subgroup": "aspiration", "label_ja": "副業実践中",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.2},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "work_side_job_wants", "group": "work_style", "subgroup": "aspiration", "label_ja": "副業したい",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.3, "income_level:low": 1.2},
     "forces_boost": {"current_solution_frustration": 0.08}},
    {"id": "work_entrepreneur_planning", "group": "work_style", "subgroup": "aspiration", "label_ja": "起業準備中",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.5, "age_band:middle": 1.3, "income_level:high": 1.3},
     "forces_boost": {"novelty_appeal": 0.1, "life_event_trigger": 0.1}},
    {"id": "work_career_change", "group": "work_style", "subgroup": "aspiration", "label_ja": "転職活動中",
     "base_rate": 0.04, "modifiers": {"age_band:young": 1.5, "age_band:middle": 1.2},
     "forces_boost": {"life_event_trigger": 0.15, "current_solution_frustration": 0.1}},
    {"id": "work_skill_up", "group": "work_style", "subgroup": "aspiration", "label_ja": "スキルアップ学習中",
     "base_rate": 0.10, "modifiers": {"age_band:young": 1.4, "age_band:middle": 1.2},
     "forces_boost": {"perceived_value": 0.05}},
    {"id": "work_certification", "group": "work_style", "subgroup": "aspiration", "label_ja": "資格取得目指す",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "work_retire_early", "group": "work_style", "subgroup": "aspiration", "label_ja": "FIRE・早期退職志向",
     "base_rate": 0.03, "modifiers": {"age_band:middle": 1.5, "income_level:high": 1.5},
     "forces_boost": {"aspirational_identity": 0.08}},

    # =========================================================================
    # GROUP: life_stage (~35 tags)
    # =========================================================================
    # --- subgroup: family ---
    {"id": "life_pregnant", "group": "life_stage", "subgroup": "family", "label_ja": "妊娠中",
     "base_rate": 0.01, "modifiers": {"gender:female": 2.0, "age_band:young": 1.2, "age_band:middle": 1.3},
     "forces_boost": {"life_event_trigger": 0.25, "unmet_need_severity": 0.15}},
    {"id": "life_newborn_parent", "group": "life_stage", "subgroup": "family", "label_ja": "新生児の親",
     "base_rate": 0.015, "modifiers": {"age_band:young": 1.2, "age_band:middle": 1.3},
     "forces_boost": {"life_event_trigger": 0.2, "unmet_need_severity": 0.15}},
    {"id": "life_toddler_parent", "group": "life_stage", "subgroup": "family", "label_ja": "幼児（1-3歳）の親",
     "base_rate": 0.04, "modifiers": {"age_band:middle": 1.4},
     "forces_boost": {"unmet_need_severity": 0.1}},
    {"id": "life_preschool_parent", "group": "life_stage", "subgroup": "family", "label_ja": "未就学児の親",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.3},
     "forces_boost": {"unmet_need_severity": 0.08}},
    {"id": "life_elementary_parent", "group": "life_stage", "subgroup": "family", "label_ja": "小学生の親",
     "base_rate": 0.06, "modifiers": {"age_band:middle": 1.4},
     "forces_boost": {}},
    {"id": "life_middle_school_parent", "group": "life_stage", "subgroup": "family", "label_ja": "中学生の親",
     "base_rate": 0.04, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.1},
     "forces_boost": {}},
    {"id": "life_high_school_parent", "group": "life_stage", "subgroup": "family", "label_ja": "高校生の親",
     "base_rate": 0.04, "modifiers": {"age_band:middle": 1.2, "age_band:senior": 1.3},
     "forces_boost": {}},
    {"id": "life_university_parent", "group": "life_stage", "subgroup": "family", "label_ja": "大学生の親",
     "base_rate": 0.04, "modifiers": {"age_band:senior": 1.5},
     "forces_boost": {"financial_risk": 0.05}},
    {"id": "life_grandparent", "group": "life_stage", "subgroup": "family", "label_ja": "孫がいる",
     "base_rate": 0.08, "modifiers": {"age_band:senior": 2.5},
     "forces_boost": {}},
    {"id": "life_single_parent", "group": "life_stage", "subgroup": "family", "label_ja": "ひとり親",
     "base_rate": 0.02, "modifiers": {"gender:female": 1.5},
     "forces_boost": {"unmet_need_severity": 0.1, "current_solution_frustration": 0.08}},
    # --- subgroup: transition ---
    {"id": "life_newlywed", "group": "life_stage", "subgroup": "transition", "label_ja": "新婚（結婚1年以内）",
     "base_rate": 0.01, "modifiers": {"age_band:young": 1.3, "age_band:middle": 1.2},
     "forces_boost": {"life_event_trigger": 0.2}},
    {"id": "life_engaged", "group": "life_stage", "subgroup": "transition", "label_ja": "婚約中",
     "base_rate": 0.008, "modifiers": {"age_band:young": 1.5, "age_band:middle": 1.2},
     "forces_boost": {"life_event_trigger": 0.2}},
    {"id": "life_marriage_hunting", "group": "life_stage", "subgroup": "transition", "label_ja": "婚活中",
     "base_rate": 0.04, "modifiers": {"age_band:young": 1.2, "age_band:middle": 1.5, "household_type:single": 2.0},
     "forces_boost": {"current_solution_frustration": 0.1, "life_event_trigger": 0.1}},
    {"id": "life_divorce_considering", "group": "life_stage", "subgroup": "transition", "label_ja": "離婚検討中",
     "base_rate": 0.01, "modifiers": {"age_band:middle": 1.3},
     "forces_boost": {"life_event_trigger": 0.2, "current_solution_frustration": 0.15}},
    {"id": "life_recently_moved", "group": "life_stage", "subgroup": "transition", "label_ja": "最近引っ越した",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.5},
     "forces_boost": {"life_event_trigger": 0.15}},
    {"id": "life_job_hunting", "group": "life_stage", "subgroup": "transition", "label_ja": "就職活動中",
     "base_rate": 0.03, "modifiers": {"age_band:young": 3.0},
     "forces_boost": {"life_event_trigger": 0.15, "current_solution_frustration": 0.1}},
    {"id": "life_new_job", "group": "life_stage", "subgroup": "transition", "label_ja": "転職・入社直後",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.5, "age_band:middle": 1.2},
     "forces_boost": {"life_event_trigger": 0.15}},
    {"id": "life_retirement_near", "group": "life_stage", "subgroup": "transition", "label_ja": "退職間近",
     "base_rate": 0.02, "modifiers": {"age_band:senior": 3.0},
     "forces_boost": {"life_event_trigger": 0.2}},
    {"id": "life_recently_retired", "group": "life_stage", "subgroup": "transition", "label_ja": "退職直後",
     "base_rate": 0.015, "modifiers": {"age_band:senior": 3.0},
     "forces_boost": {"life_event_trigger": 0.2, "current_solution_frustration": 0.1}},
    # --- subgroup: care ---
    {"id": "life_caregiver_parent", "group": "life_stage", "subgroup": "care", "label_ja": "親の介護中",
     "base_rate": 0.04, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.5},
     "forces_boost": {"unmet_need_severity": 0.15, "current_solution_frustration": 0.1}},
    {"id": "life_caregiver_spouse", "group": "life_stage", "subgroup": "care", "label_ja": "配偶者の介護中",
     "base_rate": 0.01, "modifiers": {"age_band:senior": 3.0},
     "forces_boost": {"unmet_need_severity": 0.2, "current_solution_frustration": 0.15}},
    {"id": "life_caregiver_remote", "group": "life_stage", "subgroup": "care", "label_ja": "遠距離介護",
     "base_rate": 0.02, "modifiers": {"age_band:middle": 1.5, "region:kanto": 1.3},
     "forces_boost": {"unmet_need_severity": 0.12}},
    {"id": "life_empty_nester", "group": "life_stage", "subgroup": "care", "label_ja": "子離れ（子供独立後）",
     "base_rate": 0.05, "modifiers": {"age_band:senior": 2.0, "household_type:couple": 1.5},
     "forces_boost": {"life_event_trigger": 0.1}},
    {"id": "life_single_by_choice", "group": "life_stage", "subgroup": "care", "label_ja": "独身主義",
     "base_rate": 0.04, "modifiers": {"household_type:single": 2.0, "age_band:middle": 1.3},
     "forces_boost": {}},
    {"id": "life_bereaved", "group": "life_stage", "subgroup": "care", "label_ja": "近親者を亡くした",
     "base_rate": 0.02, "modifiers": {"age_band:senior": 1.5},
     "forces_boost": {"life_event_trigger": 0.2}},

    # =========================================================================
    # GROUP: social (~25 tags)
    # =========================================================================
    # --- subgroup: community ---
    {"id": "social_pta_member", "group": "social", "subgroup": "community", "label_ja": "PTA・保護者会参加",
     "base_rate": 0.06, "modifiers": {"household_type:family_young": 1.3, "household_type:family_school": 2.0},
     "forces_boost": {}},
    {"id": "social_local_community", "group": "social", "subgroup": "community", "label_ja": "町内会・自治会参加",
     "base_rate": 0.10, "modifiers": {"age_band:senior": 1.5, "region:tohoku": 1.3},
     "forces_boost": {}},
    {"id": "social_volunteer", "group": "social", "subgroup": "community", "label_ja": "ボランティア定期参加",
     "base_rate": 0.04, "modifiers": {"age_band:senior": 1.4, "income_level:high": 1.2},
     "forces_boost": {"aspirational_identity": 0.05}},
    {"id": "social_religious", "group": "social", "subgroup": "community", "label_ja": "宗教コミュニティ参加",
     "base_rate": 0.03, "modifiers": {"age_band:senior": 1.5},
     "forces_boost": {}},
    {"id": "social_hobby_circle", "group": "social", "subgroup": "community", "label_ja": "趣味サークル・同好会",
     "base_rate": 0.08, "modifiers": {"age_band:senior": 1.3, "age_band:young": 1.2},
     "forces_boost": {"social_proof_strength": 0.05}},
    {"id": "social_sports_team", "group": "social", "subgroup": "community", "label_ja": "スポーツチーム所属",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.4, "gender:male": 1.3},
     "forces_boost": {}},
    {"id": "social_alumni_active", "group": "social", "subgroup": "community", "label_ja": "同窓会・OB会活発",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.2, "age_band:senior": 1.3},
     "forces_boost": {}},
    # --- subgroup: influence ---
    {"id": "social_influencer_micro", "group": "social", "subgroup": "influence", "label_ja": "マイクロインフルエンサー",
     "base_rate": 0.01, "modifiers": {"age_band:young": 2.0, "gender:female": 1.3},
     "forces_boost": {"social_proof_strength": 0.15, "aspirational_identity": 0.1}},
    {"id": "social_influencer_follower", "group": "social", "subgroup": "influence", "label_ja": "インフルエンサーの影響受けやすい",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.5, "gender:female": 1.2},
     "forces_boost": {"social_proof_strength": 0.1}},
    {"id": "social_review_writer", "group": "social", "subgroup": "influence", "label_ja": "レビュー・口コミ積極投稿",
     "base_rate": 0.05, "modifiers": {"age_band:middle": 1.2},
     "forces_boost": {"social_proof_strength": 0.08}},
    {"id": "social_review_checker", "group": "social", "subgroup": "influence", "label_ja": "購入前に口コミ必ず確認",
     "base_rate": 0.25, "modifiers": {"gender:female": 1.2},
     "forces_boost": {"social_proof_strength": 0.05}},
    {"id": "social_word_of_mouth", "group": "social", "subgroup": "influence", "label_ja": "友人・知人の紹介で動く",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.1, "gender:female": 1.1},
     "forces_boost": {"social_proof_strength": 0.08}},
    # --- subgroup: relationship ---
    {"id": "social_friend_large", "group": "social", "subgroup": "relationship", "label_ja": "友人・知人が多い",
     "base_rate": 0.12, "modifiers": {"age_band:young": 1.3},
     "forces_boost": {"social_proof_strength": 0.05}},
    {"id": "social_friend_small", "group": "social", "subgroup": "relationship", "label_ja": "少数の親しい友人",
     "base_rate": 0.20, "modifiers": {"age_band:middle": 1.1, "household_type:single": 1.1},
     "forces_boost": {}},
    {"id": "social_introvert", "group": "social", "subgroup": "relationship", "label_ja": "内向的・一人時間好き",
     "base_rate": 0.15, "modifiers": {"household_type:single": 1.3},
     "forces_boost": {"social_risk": 0.05}},
    {"id": "social_online_community", "group": "social", "subgroup": "relationship", "label_ja": "オンラインコミュニティ活発",
     "base_rate": 0.08, "modifiers": {"age_band:young": 1.5, "household_type:single": 1.2},
     "forces_boost": {"social_proof_strength": 0.08}},
    {"id": "social_dating_app", "group": "social", "subgroup": "relationship", "label_ja": "マッチングアプリ利用",
     "base_rate": 0.05, "modifiers": {"age_band:young": 2.0, "household_type:single": 2.5, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "social_neighborhood_close", "group": "social", "subgroup": "relationship", "label_ja": "近所付き合い密",
     "base_rate": 0.10, "modifiers": {"age_band:senior": 1.5, "region:tohoku": 1.3, "region:kyushu": 1.2},
     "forces_boost": {}},
    {"id": "social_mama_friend", "group": "social", "subgroup": "relationship", "label_ja": "ママ友コミュニティ",
     "base_rate": 0.04, "modifiers": {"gender:female": 2.0, "household_type:family_young": 2.5, "household_type:family_school": 1.5},
     "forces_boost": {"social_proof_strength": 0.08}},

    # =========================================================================
    # GROUP: sustainability (~25 tags)
    # =========================================================================
    # --- subgroup: eco ---
    {"id": "eco_active", "group": "sustainability", "subgroup": "eco", "label_ja": "環境活動に積極的",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.3, "income_level:high": 1.3},
     "forces_boost": {"aspirational_identity": 0.1}},
    {"id": "eco_recycling_strict", "group": "sustainability", "subgroup": "eco", "label_ja": "分別・リサイクル厳密",
     "base_rate": 0.15, "modifiers": {"age_band:middle": 1.1, "age_band:senior": 1.2},
     "forces_boost": {}},
    {"id": "eco_zero_waste", "group": "sustainability", "subgroup": "eco", "label_ja": "ゼロウェイスト志向",
     "base_rate": 0.01, "modifiers": {"age_band:young": 1.5, "gender:female": 1.3},
     "forces_boost": {"aspirational_identity": 0.1}},
    {"id": "eco_reusable_bag", "group": "sustainability", "subgroup": "eco", "label_ja": "マイバッグ・マイボトル常用",
     "base_rate": 0.25, "modifiers": {"gender:female": 1.2, "age_band:middle": 1.1},
     "forces_boost": {}},
    {"id": "eco_ev_interest", "group": "sustainability", "subgroup": "eco", "label_ja": "EV・電動車に関心",
     "base_rate": 0.05, "modifiers": {"income_level:high": 1.5, "age_band:middle": 1.2},
     "forces_boost": {"novelty_appeal": 0.05}},
    {"id": "eco_renewable_energy", "group": "sustainability", "subgroup": "eco", "label_ja": "再生可能エネルギー関心",
     "base_rate": 0.04, "modifiers": {"income_level:high": 1.3, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "eco_sdgs_aware", "group": "sustainability", "subgroup": "eco", "label_ja": "SDGs意識高い",
     "base_rate": 0.06, "modifiers": {"age_band:young": 1.3, "income_level:high": 1.2},
     "forces_boost": {"aspirational_identity": 0.05}},
    # --- subgroup: consumption ---
    {"id": "cons_minimalist", "group": "sustainability", "subgroup": "consumption", "label_ja": "ミニマリスト",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.4, "household_type:single": 1.5},
     "forces_boost": {"aspirational_identity": 0.08}},
    {"id": "cons_secondhand_buyer", "group": "sustainability", "subgroup": "consumption", "label_ja": "中古品積極購入",
     "base_rate": 0.10, "modifiers": {"age_band:young": 1.3, "income_level:low": 1.3},
     "forces_boost": {}},
    {"id": "cons_brand_conscious", "group": "sustainability", "subgroup": "consumption", "label_ja": "ブランド志向",
     "base_rate": 0.08, "modifiers": {"income_level:high": 1.8, "gender:female": 1.2, "age_band:young": 1.2},
     "forces_boost": {"brand_trust": 0.1}},
    {"id": "cons_ethical_consumer", "group": "sustainability", "subgroup": "consumption", "label_ja": "エシカル消費志向",
     "base_rate": 0.03, "modifiers": {"age_band:young": 1.3, "gender:female": 1.3, "income_level:high": 1.3},
     "forces_boost": {"aspirational_identity": 0.08}},
    {"id": "cons_local_first", "group": "sustainability", "subgroup": "consumption", "label_ja": "地元企業・商品優先",
     "base_rate": 0.08, "modifiers": {"age_band:senior": 1.3, "region:tohoku": 1.3, "region:hokkaido": 1.3},
     "forces_boost": {}},
    {"id": "cons_impulse_buyer", "group": "sustainability", "subgroup": "consumption", "label_ja": "衝動買い傾向",
     "base_rate": 0.10, "modifiers": {"age_band:young": 1.3, "income_level:high": 1.2},
     "forces_boost": {"financial_risk": -0.05}},
    {"id": "cons_comparison_shopper", "group": "sustainability", "subgroup": "consumption", "label_ja": "比較検討じっくり派",
     "base_rate": 0.20, "modifiers": {"age_band:middle": 1.2, "gender:female": 1.1},
     "forces_boost": {"effort_risk": 0.05}},
    # --- subgroup: lifestyle ---
    {"id": "sust_sharing_car", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "シェアリング利用（車）",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.5, "region:kanto": 1.5},
     "forces_boost": {}},
    {"id": "sust_sharing_space", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "シェアリング利用（スペース）",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.5, "region:kanto": 1.3},
     "forces_boost": {}},
    {"id": "sust_subscription_lifestyle", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "サブスク生活（5個以上）",
     "base_rate": 0.05, "modifiers": {"age_band:young": 1.4, "income_level:high": 1.3},
     "forces_boost": {}},
    {"id": "sust_digital_detox", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "デジタルデトックス志向",
     "base_rate": 0.03, "modifiers": {"age_band:middle": 1.3, "age_band:senior": 1.2},
     "forces_boost": {"behavioral_automaticity": 0.05}},
    {"id": "sust_slow_living", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "スローライフ志向",
     "base_rate": 0.04, "modifiers": {"age_band:senior": 1.5, "region:hokkaido": 1.3, "region:tohoku": 1.3},
     "forces_boost": {}},
    {"id": "sust_upcycle_repair", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "修理・アップサイクル好き",
     "base_rate": 0.03, "modifiers": {"age_band:senior": 1.3, "gender:male": 1.2},
     "forces_boost": {}},
    {"id": "sust_donation_regular", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "寄付・ふるさと納税活用",
     "base_rate": 0.08, "modifiers": {"income_level:high": 1.8, "age_band:middle": 1.2},
     "forces_boost": {}},
    {"id": "sust_fair_trade", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "フェアトレード商品購入",
     "base_rate": 0.02, "modifiers": {"gender:female": 1.3, "income_level:high": 1.4},
     "forces_boost": {"aspirational_identity": 0.05}},
    {"id": "sust_plastic_free", "group": "sustainability", "subgroup": "lifestyle", "label_ja": "プラスチックフリー志向",
     "base_rate": 0.02, "modifiers": {"age_band:young": 1.3, "gender:female": 1.3},
     "forces_boost": {}},
]


# ---------------------------------------------------------------------------
# Build the lookup structures
# ---------------------------------------------------------------------------

LIFESTYLE_TAGS: dict[str, LifestyleTagDef] = {
    d["id"]: LifestyleTagDef(**d) for d in _TAGS
}

ALL_TAG_IDS: list[str] = list(LIFESTYLE_TAGS.keys())

# Group → subgroup → [tag_ids] for LLM prompt construction
TAG_HIERARCHY: dict[str, dict[str, list[str]]] = {}
for tag in LIFESTYLE_TAGS.values():
    TAG_HIERARCHY.setdefault(tag.group, {}).setdefault(tag.subgroup, []).append(tag.id)

# Flat group → [tag_ids]
TAG_GROUPS: dict[str, list[str]] = {}
for tag in LIFESTYLE_TAGS.values():
    TAG_GROUPS.setdefault(tag.group, []).append(tag.id)


def build_compact_tag_prompt() -> str:
    """Build a compact hierarchical tag listing for LLM prompts.

    Format: [group] subgroup: tag1, tag2, tag3 | subgroup2: tag4, tag5
    """
    lines = []
    for group, subgroups in TAG_HIERARCHY.items():
        parts = []
        for subgroup, tag_ids in subgroups.items():
            parts.append(f"{subgroup}: {', '.join(tag_ids)}")
        lines.append(f"[{group}] {' | '.join(parts)}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tag assignment
# ---------------------------------------------------------------------------

def _get_demographic_value(
    demographics: dict[str, str],
    dimension: str,
) -> str | None:
    """Get the demographic value for a modifier dimension."""
    return demographics.get(dimension)


def assign_lifestyle_tags(
    age: int,
    gender: str,
    region: str,
    income_level: str,
    household_type: str,
    rng: "random.Random",
) -> list[str]:
    """Assign lifestyle tags to an agent based on conditional prevalence.

    Each tag has a base_rate modified by demographic-conditional multipliers.
    Final probability = base_rate × product(applicable_modifiers), clamped to [0, 1].

    Args:
        age: Agent age (used to determine age_band)
        gender: "male" or "female"
        region: Region enum value string
        income_level: "low", "middle", or "high"
        household_type: Household type enum value string
        rng: Random number generator for reproducibility

    Returns:
        List of assigned tag IDs
    """
    # Determine age band
    if age < 30:
        age_band = "young"
    elif age < 50:
        age_band = "middle"
    else:
        age_band = "senior"

    demographics = {
        "age_band": age_band,
        "gender": gender,
        "region": region,
        "income_level": income_level,
        "household_type": household_type,
    }

    tags: list[str] = []
    for tag_id, tag_def in LIFESTYLE_TAGS.items():
        prob = tag_def.base_rate

        for key, multiplier in tag_def.modifiers.items():
            dim, val = key.split(":", 1)
            agent_val = demographics.get(dim)
            if agent_val == val:
                prob *= multiplier

        prob = max(0.0, min(1.0, prob))
        if rng.random() < prob:
            tags.append(tag_id)

    return tags
